---
- name: Install Jenkins
  hosts: jenkins
  become: yes
  roles:
    - deploy_jenkins

- name: Install Bind 9
  hosts: bind9
  become: yes
  roles:
    - deploy_bind9

#- name: Install GitLab
#  hosts: gitlab
#  become: yes
#  roles:
#    - deploy_gitlab

- name: Install GitLab with SSL
  hosts: gitlab
  become: yes
  roles:
    - deploy_ssl_gitlab
