---
- name: Install GitLab
  hosts: gitlab
  become: yes

  tasks:
    - name: Opening the HTTP
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Add the GitLab Package Repository
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash -
      args:
        warn: no

    - name: Install GitLab
      dnf:
        name: gitlab-ce
        state: latest

#   - name: reconfigure gitlab-ce
#     shell: gitlab-ctl reconfigure

#   - name: Set up GitLab Url
#     shell: EXTERNAL_URL="http://gitlab.example.com" dnf install -y gitlab-ee
