---
- name: Install gitlab
  hosts: gitlab
  become: yes

  tasks:
    - name: Install curl policycoreutils openssh-server perl langpacks-en glibc-all-langpacks
      dnf: name={{ item }} state=latest
      loop:
        - curl
        - policycoreutils
        - openssh-server
        - perl
        - postfix
        - langpacks-en
        - glibc-all-langpacks



    - name: enable and start postfix
      service:
        name: postfix
        enabled: yes
        state: started

    - name: enable and start sshd
      service:
        name: sshd
        enabled: yes
        state: started

    - name: Opening the HTTPS
      firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Opening the HTTP
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: install gitlab packages
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh && bash && dnf install -y gitlab-ce

    - name: reconfigure gitlab-ce
      shell: gitlab-ctl reconfigure

    - name: Restart firewalld
      systemd:
        name: firewalld
        state: restarted
