---
- name: Install Nginx and Test Certificates
  hosts: test
  become: yes
  
  tasks:
    - name: Install Nginx
      dnf: name=nginx state=latest     

    - name: Upgrade PIP
      pip:
        name: pip
        extra_args: --upgrade

    - name: Install Python Dependencies
      pip:
        name: "{{ item }}"
        extra_args: --user
      with_items:
        - wheel
        - setuptools-rust
        - cryptography
        - pyOpenSSL

    - name: Generate a Self Signed OpenSSL Private Key
      openssl_privatekey:
        path: /etc/ssl/test.key

    - name: Generate a Self Signed OpenSSL Certificate Signing Request
      openssl_csr:
        path: /etc/ssl/test.csr
        privatekey_path: /etc/ssl/test.key
        common_name: client.com

    - name: Generate a Self Signed OpenSSL Certificate
      openssl_certificate:
        path: /etc/ssl/certs//test.crt
        privatekey_path: /etc/ssl/test.key
        csr_path: /etc/ssl/test.csr
        provider: selfsigned

    - name: Copy Nginx Config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644

    - name: Enable and Start Nginx
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Allow HTTP and HTTPS
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - http
        - https
